function createPDF(fname, lname, cprSix, cprFour, datetime, polno, reqno) {
    const fontNorm = localStorage.getItem('fontNorm');
    const fontBold = localStorage.getItem('fontBold');
    const fontMono = localStorage.getItem('fontMono');
    const FNAME = fname.toUpperCase();
    const LNAME = lname.toUpperCase();
    const bdayList = cprSix.match(/.{1,2}/g);
    const BDAY = bdayList[0] + ' ' + bdayList[1] + ' ' + bdayList[2];
    const CPR = cprSix + '-' + cprFour;
    const SEX = parseInt(cprFour) % 2 ? 'M' : 'F';
    let pdf = new jspdf["default"]('p', 'mm', [297, 210], true);
    const watermark = localStorage.getItem('watermark');
    const health = localStorage.getItem('health');
    const cross = localStorage.getItem('cross');
    const politi = localStorage.getItem('politi');
    const sundhed = localStorage.getItem('sundhed');
    pdf.addImage(watermark, "png", 29, 124.5, 191.6, 137.6);
    pdf.addImage(health, "png", 31.3, 12.5, 37.75, 17.8);
    pdf.addImage(cross, "png", 82.4, 21.9, 40.5, 7.0);
    pdf.addImage(politi, "png", 142.4, 22, 31.5, 6.9);
    pdf.addImage(sundhed, "png", 90, 255.9, 31.5, 4.45);
    pdf.addFileToVFS('fontNorm.ttf', fontNorm);
    pdf.addFont('fontNorm.ttf', 'sans', 'normal');
    pdf.addFileToVFS('fontBold.ttf', fontBold);
    pdf.addFont('fontBold.ttf', 'sans', 'bold');
    pdf.addFileToVFS('fontMono.ttf', fontMono);
    pdf.addFont('fontMono.ttf', 'mono', 'medium');
    const center_big_title = 75.7;
    const center_small_title = 60.2;
    const vert_offset = 74.1;
    const first_column_x = 28.4;
    const second_column_x = 95.9;
    const first_row_y = 126.7;
    const second_row_y = 140;
    const third_row_y = 153.2;
    const fourth_row_y = 173.3;
    const fifth_row_y = 186.5;
    const monospace_offset = 5.6;
    const box_offset = 0.3;
    pdf.setFont('sans', 'bold');
    pdf.setFontSize(8.3);
    pdf.text(polno, 172.85, 46.25);
    pdf.setFont('mono', 'medium');
    pdf.setFontSize(10.7);
    pdf.text(LNAME, first_column_x, first_row_y + monospace_offset);
    pdf.text(BDAY, second_column_x, first_row_y + monospace_offset);
    pdf.text(FNAME, first_column_x, second_row_y + monospace_offset);
    pdf.text(CPR, second_column_x, second_row_y + monospace_offset);
    pdf.text(SEX, first_column_x, third_row_y + monospace_offset);
    pdf.text('IKKE PÅVIST', first_column_x, fourth_row_y + monospace_offset);
    pdf.text('SARS-CoV-2 (COVID-19), RT-PCR(RNA)', second_column_x - box_offset, fourth_row_y + monospace_offset);
    pdf.text(reqno, first_column_x, fifth_row_y + monospace_offset);
    pdf.text(datetime, second_column_x - box_offset, fifth_row_y + monospace_offset);
    pdf.setFontSize(8.3);
    pdf.setFont('sans', 'normal');
    pdf.text('Dokument ID / Document ID / ID de document', 131.0, 41.02);
    pdf.text('Efternavn / Surname / Nom', first_column_x, first_row_y);
    pdf.text('Fødselsdato / Date of birth / Date de naissance', second_column_x, first_row_y);
    pdf.text('Fornavn / Given names / Prénoms', first_column_x, second_row_y);
    pdf.text("Personnummer / Personal code number / Numéro d'identite", second_column_x, second_row_y);
    pdf.text("Køn / Sex / Sexe", first_column_x, third_row_y);
    pdf.text('COVID-19 test / COVID-19 test / Test COVID-19', first_column_x, fourth_row_y);
    pdf.text('Testtype / Test type / Type de test', second_column_x - box_offset, fourth_row_y);
    pdf.text('Rekvisitionsnummer / Requisition / Réquisition', first_column_x, fifth_row_y);
    pdf.text("Prøvetagningstidspunkt / Sampling period / Période d'échantillonnage", second_column_x - box_offset, fifth_row_y);
    const col_one = 26.7;
    const col_two = 39.5;
    const col_three = 57;
    const col_four = 64.1;
    const col_five = 84.4;
    const row_explanation = 206.65;
    const row_explanation_offset = 5.25;
    pdf.text('DA:', col_one, row_explanation);
    pdf.text('ENG:', col_one, row_explanation + row_explanation_offset);
    pdf.text('FR:', col_one, row_explanation + row_explanation_offset * 2);
    pdf.setFont('sans', 'bold');
    pdf.text('"NEGATIV"', col_two, row_explanation);
    pdf.text('"NEGATIV"', col_two, row_explanation + row_explanation_offset);
    pdf.text('"NEGATIV"', col_two, row_explanation + row_explanation_offset * 2);
    pdf.setFont('sans', 'normal');
    pdf.text('eller', col_three - 1.1, row_explanation);
    pdf.text('or', col_three + 0.3, row_explanation + row_explanation_offset);
    pdf.text('ou', col_three, row_explanation + row_explanation_offset * 2);
    pdf.setFont('sans', 'bold');
    pdf.text('"IKKE PÅVIST"', col_four, row_explanation);
    pdf.text('"IKKE PÅVIST"', col_four, row_explanation + row_explanation_offset);
    pdf.text('"IKKE PÅVIST"', col_four, row_explanation + row_explanation_offset * 2);
    pdf.setFont('sans', 'normal');
    pdf.text('betyder, at testen er negativ', col_five, row_explanation);
    pdf.text('means the test is negative', col_five, row_explanation + row_explanation_offset);
    pdf.text('signifie que le test est négatif', col_five, row_explanation + row_explanation_offset * 2);
    pdf.setFont('sans', 'bold');
    pdf.setFontSize(10.3);
    pdf.text('CORONAPAS / CORONA PASSPORT / PASSEPORT CORONA', center_small_title, vert_offset - 15.3);
    pdf.setFontSize(25.9);
    pdf.text('COVID-19 TEST', center_big_title, vert_offset + 12.5);
    pdf.text('COVID-19 TEST', center_big_title, vert_offset);
    pdf.text('TEST COVID-19', center_big_title, vert_offset + 25.2);
    pdf.setFontSize(10.3);
    pdf.text('DANMARK / DENMARK / DANEMARK', 76.7, vert_offset + 35.2);
    pdf.setLineWidth(0.9);
    pdf.line(24, 36.4, 187.7, 36.4);
    pdf.line(24, 118.6, 187.7, 118.6);
    const box_vert_begin = 163.5;
    const box_vert_end = 199.5;
    pdf.setLineWidth(0.8);
    pdf.line(24, box_vert_begin, 187.7, box_vert_begin);
    pdf.line(24, box_vert_end, 187.7, box_vert_end);
    pdf.line(24.44, box_vert_begin, 24.44, box_vert_end);
    pdf.line(187.34, box_vert_begin, 187.34, box_vert_end);
    pdf.setFontSize(8.3);
    pdf.setFont('sans', 'normal');
    const footer_first_line = 229.2;
    const footer_offset = 4.3;
    const footer_second_line = footer_first_line + footer_offset;
    const footer_third_line = footer_first_line + footer_offset * 2;
    const footer_fourth_line = footer_first_line + footer_offset * 3;
    const footer_fifth_line = footer_first_line + footer_offset * 4;
    const footer_first_col = 24;
    const footer_second_col = 77.5;
    const footer_third_col = 131;
    pdf.text('Ved spørgsmål til dette dokument skal', footer_first_col, footer_first_line);
    pdf.text('henvendelse rettes til den lokale danske', footer_first_col, footer_second_line);
    pdf.text('ambassade eller Udenrigsministeriet', footer_first_col, footer_third_line);
    pdf.text('+45 33 92 11 12', footer_first_col, footer_fourth_line);
    pdf.text('Questions regarding this document can', footer_second_col, footer_first_line);
    pdf.text('be directed to the local Danish embassy', footer_second_col, footer_second_line);
    pdf.text('or Ministry of Foreign Affairs of', footer_second_col, footer_third_line);
    pdf.text('Denmark +45 33 92 11 12', footer_second_col, footer_fourth_line);
    pdf.text("D’éventuelles questions au sujet de ce ", footer_third_col, footer_first_line);
    pdf.text("document peuvent être adressées à", footer_third_col, footer_second_line);
    pdf.text("l'ambassade locale du Danemark, ou au", footer_third_col, footer_third_line);
    pdf.text("Ministère danois des affaires étrangères", footer_third_col, footer_fourth_line);
    pdf.text("en composant le +45 33 92 11 12", footer_third_col, footer_fifth_line);
    pdf.setLineWidth(0.6);
    pdf.line(24, 223.8, 187.7, 223.8);
    pdf.save('Coronapas - COVID-19.pdf');
}
